name: Test Lambda code

inputs:
  lambda-directory:
    required: true
  lambda-name:
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        if [ -d tests ] && [ -f yarn.lock ]; then
          yarn install
          yarn test
        else
          echo "No tests folder detected"
        fi
      working-directory: ${{ inputs.lambda-directory }}
      shell: bash
