audit-logs:
  - "lambda-code/audit-logs/**"
audit-logs-archiver:
  - "lambda-code/audit-logs-archiver/**"
cognito-email-sender:
  - "lambda-code/cognito-email-sender/**"
cognito-pre-sign-up:
  - "lambda-code/cognito-pre-sign-up/**"
form-archiver:
  - "lambda-code/form-archiver/**"
load-testing:
  - "lambda-code/load-testing/**"
nagware:
  - "lambda-code/nagware/**"
notify-slack:
  - "lambda-code/notify-slack/**"
reliability:
  - "lambda-code/reliability/**"
reliability-dlq-consumer:
  - "lambda-code/reliability-dlq-consumer/**"
response-archiver:
  - "lambda-code/response-archiver/**"
submission:
  - "lambda-code/submission/**"
vault-integrity:
  - "lambda-code/vault-integrity/**"
prisma-migration:
  - "lambda-code/prisma-migration/**"
api-end-to-end-test:
  - "lambda-code/api-end-to-end-test/**"
