version: "3.8"
volumes:
  localstack:
services:
  localstack:
    container_name: "GCForms_LocalStack"
    image: localstack/localstack-pro:latest@sha256:adf0f4da63b4db720d6a456b899a88d5f6d3028f7775010a3d2343edca719d8a
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - SERVICES=cloudwatch,dynamodb,ec2,events,iam,kinesis,kms,lambda,logs,s3,secretsmanager,sns,sqs
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=60
      - LAMBDA_SYNCHRONOUS_CREATE=1
      - LAMBDA_IGNORE_ARCHITECTURE=1
      - DYNAMODB_SHARE_DB=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PERSISTENCE=1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - SNAPSHOT_LOAD_STRATEGY=ON_STARTUP
      - SNAPSHOT_FLUSH_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack:/var/lib/localstack"

  db:
    container_name: "GCForms_DB"
    image: postgres:13-alpine@sha256:95f1dfacf62e4842d1c62866dd03034d7d68e0771b38a331daa5757ec2d4a86d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=chummy
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
    restart: always
  redis:
    container_name: "GCForms_Redis"
    restart: always
    image: redis:6-alpine@sha256:3fcb624d83a9c478357f16dc173c58ded325ccc5fd2a4375f3916c04cc579f70
    ports:
      - "6379:6379"
    expose:
      - "6379"
