ARG NODE_VERSION=24-arm64
ARG PNPM_VERSION=11.22.0+sha512.1ff870c4c6133dfd88fb2afc46dd13d47f09c9794b438c6fdb47ca98caf3bc16381ee0be93a091b8e3824cf01f889f46d7d9e20910fb0be1ab0fb5baa80dd621

FROM public.ecr.aws/lambda/nodejs:$NODE_VERSION AS open_telemetry

# Install utilities
RUN dnf install -y unzip wget

# Download the OpenTelemetry Layer with AppSignals Support
RUN wget https://github.com/aws-observability/aws-otel-js-instrumentation/releases/latest/download/layer.zip -O /tmp/layer.zip

# Extract and include Lambda layer contents
RUN mkdir -p /opt
WORKDIR /opt
RUN unzip /tmp/layer.zip -d ./
RUN chmod -R 755 /opt/

FROM public.ecr.aws/lambda/nodejs:$NODE_VERSION AS build

ARG LAMBDA_NAME

WORKDIR /usr/app

COPY package.json \
     pnpm-lock.yaml \
     pnpm-workspace.yaml \
     ./

COPY --parents ./lambda-code/$LAMBDA_NAME/package.json \
               ./lambda-code/$LAMBDA_NAME/tsconfig.json \
               ./lambda-code/$LAMBDA_NAME/src \
               ./

RUN corepack enable pnpm && pnpm install --frozen-lockfile && pnpm build

RUN pnpm --filter $LAMBDA_NAME deploy --prod ./standalone-build

FROM public.ecr.aws/lambda/nodejs:$NODE_VERSION

ENV AWS_LAMBDA_EXEC_WRAPPER=/opt/otel-instrument

WORKDIR $LAMBDA_TASK_ROOT

COPY --from=build /usr/app/standalone-build/package.json ./
COPY --from=build /usr/app/standalone-build/node_modules ./node_modules
COPY --from=build /usr/app/standalone-build/build ./
COPY --from=open_telemetry /opt /opt

CMD ["main.handler"]