version: "3.8"
volumes:
  localstack_data:
services:
  localstack:
    container_name: "GCForms_LocalStack"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - SERVICES=cloudwatch,dynamodb,ec2,events,iam,kinesis,kms,lambda,logs,s3,secretsmanager,sns,sqs
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=60
      - LAMBDA_SYNCHRONOUS_CREATE=1
      - LAMBDA_IGNORE_ARCHITECTURE=1
      - DYNAMODB_SHARE_DB=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack_data:/var/lib/localstack" # mount Docker volume
  db:
    container_name: "GCForms_DB"
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=chummy
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
    restart: always
  redis:
    container_name: "GCForms_Redis"
    restart: always
    image: redis:latest@sha256:2976bc0437deff693af2dcf081a1d1758de8b413e6de861151a5a136c25eb9e4
    ports:
      - "6379:6379"
    expose:
      - "6379"
