packages:
  - "lambda-code/submission"
  # - "lambda-code/*"

injectWorkspacePackages: true

blockExoticSubdeps: true

# minimumReleaseAge: 10080 # 7 days
minimumReleaseAge: 0 # to delete and replace by previous line

catalog:
  "@biomejs/biome": ^2.5.9
  "@types/aws-lambda": ^8.10.162
  "@types/node": ^26.2.0
  typescript: ^7.0.2
  vitest: ^4.1.11
  "@aws-sdk/client-dynamodb": ^3.1113.0
  "@aws-sdk/client-s3": ^3.1113.0
  "@aws-sdk/client-sqs": ^3.1113.0
  "@aws-sdk/lib-dynamodb": ^3.1113.0
  uuid: ^14.0.2