packages:
  - "lambda-code/*"

injectWorkspacePackages: true

blockExoticSubdeps: true

# minimumReleaseAge: 10080 # 7 days
minimumReleaseAge: 0 # to delete and replace by previous line

catalog:
  "@aws-sdk/client-dynamodb": ^3.1113.0
  "@aws-sdk/client-s3": ^3.1113.0
  "@aws-sdk/client-sqs": ^3.1113.0
  "@aws-sdk/lib-dynamodb": ^3.1113.0
  "@aws-sdk/client-lambda": ^3.1113.0
  "@gcforms/connectors": ^3.0.1
  "@gcforms/core": ^2.2.26
  "@gcforms/database": 1.1.10
  "@gcforms/types": ^1.0.38
  axios: ^1.19.0
  uuid: ^14.0.2