name: Get infrastructure version to deploy

inputs:
  is-tagged:
    description: "Is this for the release of a tagged version?  This action will wait for the tag to exist if so."
    required: true
outputs:
  version:
    description: "Infrastructure version to deploy"
    value: ${{ steps.output-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Get version, release PR branch
      if: inputs.is-tagged == 'false' && startsWith(github.head_ref, 'release-please--')
      env:
        GITHUB_HEAD_REF: ${{ github.head_ref }}
      run: echo "version=$GITHUB_HEAD_REF" >> $GITHUB_ENV
      shell: bash

    - name: Get version, perform release of tag
      if: inputs.is-tagged == 'true'
      run: echo "version=v$(cat version.txt)" >> $GITHUB_ENV
      shell: bash

    - name: Wait for tag to exist
      if: inputs.is-tagged == 'true'
      run: ./.github/workflows/scripts/wait-for-tag.sh ${{ env.version }}
      shell: bash

    - name: Fail if no version set
      if: env.version == ''   
      run: exit 1
      shell: bash

    - name: Output version
      id: output-version
      run: echo "version=${{ env.version }}" >> $GITHUB_OUTPUT
      shell: bash
