version: "3"

services:
  iac:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        AWS_SAM_VERSION: "1.50.0"
        AWS_SAM_CHECKSUM: "093fc2cc40b098321dcc8635abe468642b72f8658821c9243a9357e400734207"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      AWS_LOCALSTACK: "True"
      DEVCONTAINER: "True"
      TF_VAR_cognito_client_id: ""
      TF_VAR_cognito_endpoint_url: ""
      TF_VAR_cognito_user_pool_arn: ""
      TF_VAR_email_address_contact_us: ""
      TF_VAR_email_address_support: ""
      TF_VAR_localstack_host: "host.docker.internal"
      TF_VAR_region: "ca-central-1"
      
  localstack:
    image: localstack/localstack@sha256:e012933b1122dede2c2ffc686b8ccbf9e6e5db3e20562d340d5917dbf4e019e4
    hostname: localstack
    volumes:
      - "./data:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/init_localstack:/docker-entrypoint-initaws.d"
    ports:
      - 4566:4566
    environment:
      - SERVICES=ec2,dynamodb,kms,sqs,s3,sns
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock`
      - DEBUG=1
