AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM template for local lambda testing for GC Forms

Parameters:
  AppName:
    Type: String
    Description: Name of application (no spaces). Value must be globally unique
    Default: FormsTest
  REGION:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Name of application (no spaces). Value must be globally unique
    Default: ca-central-1
  DBUser:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "postgres"
  DBPassword:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "chummy"
  DBHost:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "host.docker.internal"
  DBName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "formsDB"
  TOKEN_SECRET:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "somesecretstring"
  SQS_URL:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "http://host.docker.internal:4566/000000000000/submission_processing.fifo"
  NOTIFY_API_KEY:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "NOTIFY API KEY"
  TEMPLATE_ID:
    Type: String
    Default: "8d597a1b-a1d6-4e3c-8421-042a2b4158b7"
  TEMPORARY_TOKEN_TEMPLATE_ID:
    Type: String
    Default: "b6885d06-d10a-422a-973f-05e274d9aa86"

Globals:
  Function:
    Runtime: nodejs14.x
    Tags:
      Environment:
        Ref: Environment
        Name:
          Ref: AppName

Resources:
  Submission:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-${AppName}-submission
      CodeUri: ../submission/
      Handler: submission.handler
      Layers:
        - Ref: SubmissionLayer
      Environment:
        Variables:
          REGION:
            Ref: REGION
          SQS_URL:
            Ref: SQS_URL

  Reliability:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-${AppName}-reliability
      CodeUri: ../reliability/
      Handler: reliability.handler
      Timeout: 300
      Layers:
        - Ref: ReliabilityLayer
      Environment:
        Variables:
          REGION:
            Ref: REGION
          NOTIFY_API_KEY:
            Ref: NOTIFY_API_KEY
          TEMPLATE_ID:
            Ref: TEMPLATE_ID
          PGUSER:
            Ref: DBUser
          PGPASSWORD:
            Ref: DBPassword
          PGHOST:
            Ref: DBHost
          PGDATABASE:
            Ref: DBName

  Archiver:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-${AppName}-Archiver
      CodeUri: ../archive_form_responses/
      Handler: archiver.handler
      Layers:
        - Ref: ArchiverLayer
      Environment:
        Variables:
          REGION:
            Ref: REGION
          DYNAMODB_VAULT_TABLE_NAME:
            Ref: Vault
          ARCHIVING_S3_BUCKET:
            Ref: forms-local-archive-storage
          SNS_ERROR_TOPIC_ARN:
            Ref: arn:aws:sns:us-east-1:000000000000:alert-critical

  DeadLetterQueueConsumer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-${AppName}-Dead-letter-queue-consumer
      CodeUri: ../dead_letter_queue_consumer/
      Handler: dead_letter_queue_consumer.handler
      Timeout: 300
      Layers:
        - Ref: DeadLetterQueueConsumerLayer
      Environment:
        Variables:
          SQS_DEAD_LETTER_QUEUE_URL:
            Ref: http://localhost:4566/000000000000/deadletter_queue.fifo
          SQS_SUBMISSION_PROCESSING_QUEUE_URL:
            Ref: http://localhost:4566/000000000000/submission_processing.fifo

  ArchiveFormTemplates:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-${AppName}-ArchiveFormTemplates
      CodeUri: ../archive_form_templates/
      Handler: archiver.handler
      Layers:
        - Ref: ArchiveFormTemplatesLayer
      Environment:
        Variables:
          REGION:
            Ref: REGION
          PGUSER:
            Ref: DBUser
          PGPASSWORD:
            Ref: DBPassword
          PGHOST:
            Ref: DBHost
          PGDATABASE:
            Ref: DBName
  AuditLogs:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-${AppName}-AuditLogs
      CodeUri: ../audit_logs/
      Handler: audit_logs.handler
      Layers:
        - Ref: AuditLogsLayer
      Environment:
        Variables:
          REGION:
            Ref: REGION
          SNS_ERROR_TOPIC_ARN:
            Ref: arn:aws:sns:us-east-1:000000000000:alert-critical

  ArchiveFormResponses:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-${AppName}-ArchiveFormResponses
      CodeUri: ../archive_form_responses/
      Handler: archiver.handler
      Layers:
        - Ref: ArchiveFormResponsesLayer
      Environment:
        Variables:
          REGION:
            Ref: REGION
          DYNAMODB_VAULT_TABLE_NAME:
            Ref: Vault
          ARCHIVING_S3_BUCKET:
            Ref: forms-local-archive-storage
          VAULT_FILE_STORAGE_S3_BUCKET:
            Ref: forms-local-vault-file-storage
          SNS_ERROR_TOPIC_ARN:
            Ref: arn:aws:sns:ca-central-1:000000000000:alert-critical

  SubmissionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${Environment}-${AppName}-submission-layer
      ContentUri: ../submission/
      CompatibleRuntimes:
        - nodejs14.x

  ReliabilityLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${Environment}-${AppName}-reliability-layer
      ContentUri: ../reliability/
      CompatibleRuntimes:
        - nodejs14.x

  ArchiverLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${Environment}-${AppName}-archiver-layer
      ContentUri: ../archive_form_responses/
      CompatibleRuntimes:
        - nodejs14.x

  ArchiveFormTemplatesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${Environment}-${AppName}-archive_form_templates-layer
      ContentUri: ../archive_form_templates/
      CompatibleRuntimes:
        - nodejs14.x

  DeadLetterQueueConsumerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${Environment}-${AppName}-dead-letter-queue-consumer-layer
      ContentUri: ../dead_letter_queue_consumer/
      CompatibleRuntimes:
        - nodejs14.x
  AuditLogsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${Environment}-${AppName}-audit_logs_node_packages
      ContentUri: ../audit_logs/
      CompatibleRuntimes:
        - nodejs14.x
