AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM template for local lambda testing for GC Forms

Parameters:
  AppName:
    Type: String
    Description: Name of application (no spaces). Value must be globally unique
    Default: FormsTest
  REGION:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Name of application (no spaces). Value must be globally unique
    Default: ca-central-1
  DBUser:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "postgres"
  DBPassword:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "chummy"
  DBHost:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "host.docker.internal"
  DBName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "formsDB"
  TOKEN_SECRET:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "somesecretstring"
  SQS_URL:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "http://host.docker.internal:4566/000000000000/submission_processing.fifo"
  NOTIFY_API_KEY:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "NOTIFY API KEY"
  TEMPLATE_ID:
    Type: String
    Default: "8d597a1b-a1d6-4e3c-8421-042a2b4158b7"
  TEMPORARY_TOKEN_TEMPLATE_ID:
    Type: String
    Default: "b6885d06-d10a-422a-973f-05e274d9aa86"
  ENVIRONMENT:
    Type: String
    Default: "local"
  DOMAIN:
    Type: String
    Default: "localhost:3000"

Globals:
  Function:
    Runtime: nodejs18.x
    Tags:
      Environment:
        Ref: Environment
        Name:
          Ref: AppName

Resources:
  Submission:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-${AppName}-submission
      CodeUri: ../submission/
      Runtime: nodejs18.x
      Handler: submission.handler
      Layers:
        - Ref: SubmissionLayer
      Environment:
        Variables:
          REGION:
            Ref: REGION
          SQS_URL:
            Ref: SQS_URL

  Reliability:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-${AppName}-reliability
      CodeUri: ../reliability/
      Handler: reliability.handler
      Runtime: nodejs18.x
      Policies:
        - SQSPollerPolicy:
          QueueName: arn:aws:sqs:ca-central-1:000000000000:submission_processing.fifo
        - DynamoDBCrudPolicy:
          TableName: arn:aws:dynamodb:ca-central-1:000000000000:ReliabilityQueue
      Events:
        Submission:
          Type: SQS
          Properties:
            BatchSize: 1
            Enabled: true
            Queue: arn:aws:sqs:ca-central-1:000000000000:submission_processing.fifo
      Timeout: 300
      Layers:
        - Ref: ReliabilityLayer
      Environment:
        Variables:
          REGION:
            Ref: REGION
          NOTIFY_API_KEY:
            Ref: NOTIFY_API_KEY
          TEMPLATE_ID:
            Ref: TEMPLATE_ID
          PGUSER:
            Ref: DBUser
          PGPASSWORD:
            Ref: DBPassword
          PGHOST:
            Ref: DBHost
          PGDATABASE:
            Ref: DBName

  DeadLetterQueueConsumer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-${AppName}-Dead-letter-queue-consumer
      CodeUri: ../dead_letter_queue_consumer/
      Handler: dead_letter_queue_consumer.handler
      Role: arn:aws:iam::000000000000:role/iam_for_lambda
      Runtime: nodejs18.x
      Timeout: 300
      Layers:
        - Ref: DeadLetterQueueConsumerLayer
      Environment:
        Variables:
          SQS_DEAD_LETTER_QUEUE_URL:
            Ref: http://localhost:4566/000000000000/reliability_deadletter_queue.fifo
          SQS_SUBMISSION_PROCESSING_QUEUE_URL:
            Ref: http://localhost:4566/000000000000/submission_processing.fifo

  ArchiveFormTemplates:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-${AppName}-ArchiveFormTemplates
      CodeUri: ../archive_form_templates/
      Handler: archiver.handler
      Role: arn:aws:iam::000000000000:role/iam_for_lambda
      Runtime: nodejs18.x
      Layers:
        - Ref: ArchiveFormTemplatesLayer
      Environment:
        Variables:
          REGION:
            Ref: REGION
          PGUSER:
            Ref: DBUser
          PGPASSWORD:
            Ref: DBPassword
          PGHOST:
            Ref: DBHost
          PGDATABASE:
            Ref: DBName

  AuditLogs:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-${AppName}-AuditLogs
      CodeUri: ../audit_logs/
      Handler: audit_logs.handler
      Role: arn:aws:iam::000000000000:role/iam_for_lambda
      Runtime: nodejs18.x
      Events:
        AuditLogs:
          Type: SQS
          Properties:
            BatchSize: 10
            Enabled: true
            Queue: arn:aws:sqs:ca-central-1:000000000000:audit_log_queue
      Layers:
        - Ref: AuditLogsLayer
      Environment:
        Variables:
          REGION:
            Ref: REGION
          SNS_ERROR_TOPIC_ARN:
            Ref: arn:aws:sns:us-east-1:000000000000:alert-critical

  ArchiveFormResponses:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-${AppName}-ArchiveFormResponses
      CodeUri: ../archive_form_responses/
      Handler: archiver.handler
      Role: arn:aws:iam::000000000000:role/iam_for_lambda
      Runtime: nodejs18.x
      Layers:
        - Ref: ArchiveFormResponsesLayer
      Environment:
        Variables:
          REGION:
            Ref: REGION
          DYNAMODB_VAULT_TABLE_NAME:
            Ref: Vault
          ARCHIVING_S3_BUCKET:
            Ref: forms-local-archive-storage
          VAULT_FILE_STORAGE_S3_BUCKET:
            Ref: forms-local-vault-file-storage
          SNS_ERROR_TOPIC_ARN:
            Ref: arn:aws:sns:ca-central-1:000000000000:alert-critical

  Nagware:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-${AppName}-Nagware
      CodeUri: ../nagware/
      Handler: nagware.handler
      Role: arn:aws:iam::000000000000:role/iam_for_lambda
      Runtime: nodejs18.x
      Layers:
        - Ref: NagWareLayer
      Environment:
        Variables:
          REGION:
            Ref: REGION
          DYNAMODB_VAULT_TABLE_NAME:
            Ref: Vault
          SNS_ERROR_TOPIC_ARN:
            Ref: arn:aws:sns:ca-central-1:000000000000:alert-critical
          NOTIFY_API_KEY:
            Ref: NOTIFY_API_KEY
          TEMPLATE_ID:
            Ref: TEMPLATE_ID
          PGUSER:
            Ref: DBUser
          PGPASSWORD:
            Ref: DBPassword
          PGHOST:
            Ref: DBHost
          PGDATABASE:
            Ref: DBName
          ENVIRONMENT:
            Ref: ENVIRONMENT
          DOMAIN:
            Ref: DOMAIN

  ArchiveAuditLogs:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-${AppName}-ArchiveAuditLogs
      CodeUri: ../archive_audit_logs/
      Handler: archiver.handler
      Role: arn:aws:iam::000000000000:role/iam_for_lambda
      Runtime: nodejs18.x
      Layers:
        - Ref: ArchiveAuditLogsLayer
      Environment:
        Variables:
          REGION:
            Ref: REGION
          SNS_ERROR_TOPIC_ARN:
            Ref: arn:aws:sns:us-east-1:000000000000:alert-critical
  VaultDataIntegrityCheck:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-${AppName}-VaultDataIntegrityCheck
      CodeUri: ../vault_data_integrity_check/
      Handler: vault_data_integrity_check.handler

  SubmissionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${Environment}-${AppName}-submission-layer
      ContentUri: ../submission/
      CompatibleRuntimes:
        - nodejs18.x

  ReliabilityLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${Environment}-${AppName}-reliability-layer
      ContentUri: ../reliability/
      CompatibleRuntimes:
        - nodejs18.x

  ArchiveFormResponsesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${Environment}-${AppName}-archive-form-responses-layer
      ContentUri: ../archive_form_responses/
      CompatibleRuntimes:
        - nodejs18.x

  ArchiveFormTemplatesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${Environment}-${AppName}-archive_form_templates-layer
      ContentUri: ../archive_form_templates/
      CompatibleRuntimes:
        - nodejs18.x

  DeadLetterQueueConsumerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${Environment}-${AppName}-dead-letter-queue-consumer-layer
      ContentUri: ../dead_letter_queue_consumer/
      CompatibleRuntimes:
        - nodejs18.x

  AuditLogsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${Environment}-${AppName}-audit_logs_node_packages
      ContentUri: ../audit_logs/
      CompatibleRuntimes:
        - nodejs18.x

  NagWareLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${Environment}-${AppName}-nagware-layer
      ContentUri: ../nagware/
      CompatibleRuntimes:
        - nodejs18.x

  ArchiveAuditLogsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${Environment}-${AppName}-archive_audit_logs-layer
      ContentUri: ../archive_audit_logs/
      CompatibleRuntimes:
        - nodejs18.x
