# Default config is merged with the overrides in this file.
# https://zitadel.com/docs/self-hosting/manage/configure#runtime-configuration-file

Log:
  Level: "info"

Port: 8080
ExternalPort: 8080
ExternalSecure: false
TLS:
  Enabled: false

Database:
  postgres:
    Port: 5432
    User:
      SSL:
        Mode: "require"
    Admin:
      SSL:
        Mode: "require"
    MaxOpenConns: 15
    MaxIdleConns: 10
    MaxConnLifetime: "1h"
    MaxConnIdleTime: "5m"

DefaultInstance:
  LoginPolicy:
    AllowRegister: false
    ForceMFA: true
    HidePasswordReset: true
  OIDCSettings:
    AccessTokenLifetime: "0.5h"
    IdTokenLifetime: "0.5h"
    RefreshTokenIdleExpiration: "720h"
    RefreshTokenExpiration: "2160h"

OIDC:
  DefaultAccessTokenLifetime: "0.5h"
  DefaultIdTokenLifetime: "0.5h"
  DefaultRefreshTokenIdleExpiration: "720h"
  DefaultRefreshTokenExpiration: "2160h"
