# Default config is merged with the overrides in this file.
# https://zitadel.com/docs/self-hosting/manage/configure#runtime-configuration-file

Log:
  Level: 'info'

Port: 8080
ExternalPort: 443
ExternalSecure: true
TLS:
  Enabled: true
  KeyPath: '/app/private.key'
  CertPath: '/app/certificate.crt'

Database:
  postgres:
    Port: 5432
    User:
      SSL:
        Mode: 'require'
    Admin:
      SSL:
        Mode: 'require'

DefaultInstance:
  LoginPolicy:
    AllowRegister: false
    ForceMFA: true
    HidePasswordReset: true
  OIDCSettings:
    AccessTokenLifetime: '1h'
    IdTokenLifetime: '1h'
    RefreshTokenIdleExpiration: '720h'
    RefreshTokenExpiration: '2160h'

OIDC:
  DefaultAccessTokenLifetime: '1h'
  DefaultIdTokenLifetime: '1h'
  DefaultRefreshTokenIdleExpiration: '720h'
  DefaultRefreshTokenExpiration: '2160h'