FROM ghcr.io/zitadel/zitadel:v2.55.0@sha256:91f6c14d44247c7c575536a0ca6228fc0f7f6b59d8368c122f69ac9d39cd3eec

COPY ./docker/certificate.crt /usr/local/share/ca-certificates/certificate.crt
COPY ./docker/private.key /usr/local/share/ca-certificates/private.key
