name: "Diff comment"

on:
  workflow_call:
    inputs:
      base:
        required: true
        type: string
        description: The base for the compare (SHA, tag or branch)
      ref:
        required: true
        type: string
        description: The reference to compare against base (SHA, tag or branch)

jobs:
  tag-compare:
    runs-on: ubuntu-latest
    steps:

      - name: Delete previous comments
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: comments } = await github.rest.issues.listComments({...context.repo, issue_number: context.issue.number});
            const comment = comments.find(comment => comment.user.type === "Bot" && comment.body.indexOf("Version diff") > -1);
            if (comment) {
              await github.rest.issues.deleteComment({...context.repo, comment_id: comment.id});
            }

      - name: Add version diff comment
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: "## Version diff\nhttps://github.com/cds-snc/forms-terraform/compare/${{ inputs.base }}...${{ inputs.ref }}"
            })
