on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release Generator

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        id: sre_app_token
        with:
          app_id: ${{ secrets.CDS_RELEASE_BOT_APP_ID }}
          private_key: ${{ secrets.CDS_RELEASE_BOT_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        with:
          token: ${{ steps.sre_app_token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
