name: "Terragrunt plan PRODUCTION"

on:
  pull_request:
    branches:
      - "develop"

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  APP_ENV: production
  APP_DOMAINS: ${{ vars.PRODUCTION_APP_DOMAINS}}
  AWS_ACCOUNT_ID: ${{ vars.PRODUCTION_AWS_ACCOUNT_ID }}
  AWS_REGION: ca-central-1
  CONFTEST_VERSION: 0.36.0
  TERRAFORM_VERSION: 1.6.6
  TERRAGRUNT_VERSION: 0.54.8
  TF_INPUT: false
  TF_VAR_ecs_secret_token: ${{ secrets.PRODUCTION_TOKEN_SECRET }}
  TF_VAR_recaptcha_secret: ${{secrets.PRODUCTION_RECAPTCHA_SITE_SECRET}}
  TF_VAR_recaptcha_public: 6LfuLrQnAAAAAK9Df3gem4XLMRVY2Laq6t2fhZhZ
  TF_VAR_notify_api_key: ${{ secrets.PRODUCTION_NOTIFY_API_KEY }}
  TF_VAR_freshdesk_api_key: ${{ secrets.PRODUCTION_FRESHDESK_API_KEY }}
  TF_VAR_rds_db_password: ${{ secrets.PRODUCTION_DB_PASSWORD }}
  TF_VAR_slack_webhook: ${{ secrets.PRODUCTION_SLACK_WEBHOOK }}
  TF_VAR_gc_notify_callback_bearer_token: ${{ secrets.PRODUCTION_GC_NOTIFY_CALLBACK_BEARER_TOKEN }}
  TF_VAR_gc_temp_token_template_id: 61cec9c4-64ca-4e4d-b4d2-a0e931c44422
  TF_VAR_gc_template_id: 92096ac6-1cc5-40ae-9052-fffdb8439a90
  TF_VAR_cognito_code_template_id: 8dde39b6-05b9-43ce-807f-c2364ed3bdb6
  TF_VAR_email_address_contact_us: ${{ vars.PRODUCTION_CONTACT_US_EMAIL }}
  TF_VAR_email_address_support: ${{ vars.PRODUCTION_SUPPORT_EMAIL }}
jobs:
  terragrunt-plan:
    if: ${{startsWith(github.head_ref, 'release-please--')}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      # Setup Terraform, Terragrunt, and Conftest
      - name: Setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/forms-terraform-plan
          role-session-name: TFPlan
          aws-region: ${{ env.AWS_REGION }}

      # No dependencies
      - name: Terragrunt plan ecr
        uses: cds-snc/terraform-plan@28d2efe5155573489fa5b5816fad20d44d1f274b # v3.0.7
        with:
          directory: "env/cloud/ecr"
          comment-delete: "true"
          comment-title: "Production: ecr"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      - name: Terragrunt plan hosted_zone
        uses: cds-snc/terraform-plan@28d2efe5155573489fa5b5816fad20d44d1f274b # v3.0.7
        with:
          directory: "env/cloud/hosted_zone"
          comment-delete: "true"
          comment-title: "Production: hosted_zone"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      - name: Terragrunt plan kms
        uses: cds-snc/terraform-plan@28d2efe5155573489fa5b5816fad20d44d1f274b # v3.0.7
        with:
          directory: "env/cloud/kms"
          comment-delete: "true"
          comment-title: "Production: kms"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      - name: Terragrunt plan oidc_roles
        uses: cds-snc/terraform-plan@28d2efe5155573489fa5b5816fad20d44d1f274b # v3.0.7
        with:
          directory: "env/cloud/oidc_roles"
          comment-delete: "true"
          comment-title: "Production: oidc_roles"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      - name: Terragrunt plan sqs
        uses: cds-snc/terraform-plan@28d2efe5155573489fa5b5816fad20d44d1f274b # v3.0.7
        with:
          directory: "env/cloud/sqs"
          comment-delete: "true"
          comment-title: "Production: sqs"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      - name: Terragrunt plan secrets
        uses: cds-snc/terraform-plan@28d2efe5155573489fa5b5816fad20d44d1f274b # v3.0.7
        with:
          directory: "env/cloud/secrets"
          comment-delete: "true"
          comment-title: "Production: secrets"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      - name: Terragrunt plan s3
        uses: cds-snc/terraform-plan@28d2efe5155573489fa5b5816fad20d44d1f274b # v3.0.7
        with:
          directory: "env/cloud/s3"
          comment-delete: "true"
          comment-title: "Production: s3"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      # Depends on kms
      - name: Terragrunt plan sns
        uses: cds-snc/terraform-plan@28d2efe5155573489fa5b5816fad20d44d1f274b # v3.0.7
        with:
          directory: "env/cloud/sns"
          comment-delete: "true"
          comment-title: "Production: sns"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      - name: Install Cognito Lambda deps
        run: ./aws/cognito/lambda/deps.sh install

      - name: Terragrunt plan cognito
        uses: cds-snc/terraform-plan@28d2efe5155573489fa5b5816fad20d44d1f274b # v3.0.7
        with:
          directory: "env/cloud/cognito"
          comment-delete: "true"
          comment-title: "Production: cognito"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      - name: Remove Cognito Lambda deps
        run: ./aws/cognito/lambda/deps.sh delete

      - name: Terragrunt plan network
        uses: cds-snc/terraform-plan@28d2efe5155573489fa5b5816fad20d44d1f274b # v3.0.7
        with:
          directory: "env/cloud/network"
          comment-delete: "true"
          comment-title: "Production: network"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      - name: Terragrunt plan dynamodb
        uses: cds-snc/terraform-plan@28d2efe5155573489fa5b5816fad20d44d1f274b # v3.0.7
        with:
          directory: "env/cloud/dynamodb"
          comment-delete: "true"
          comment-title: "Production: dynamodb"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      # Depends on network
      - name: Terragrunt plan load_balancer
        uses: cds-snc/terraform-plan@28d2efe5155573489fa5b5816fad20d44d1f274b # v3.0.7
        with:
          directory: "env/cloud/load_balancer"
          comment-delete: "true"
          comment-title: "Production: load_balancer"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      - name: Terragrunt plan redis
        uses: cds-snc/terraform-plan@28d2efe5155573489fa5b5816fad20d44d1f274b # v3.0.7
        with:
          directory: "env/cloud/redis"
          comment-delete: "true"
          comment-title: "Production: redis"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      - name: Terragrunt plan rds
        uses: cds-snc/terraform-plan@28d2efe5155573489fa5b5816fad20d44d1f274b # v3.0.7
        with:
          directory: "env/cloud/rds"
          comment-delete: "true"
          comment-title: "Production: rds"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      # Depends on everything

      - name: Terragrunt plan app
        uses: cds-snc/terraform-plan@28d2efe5155573489fa5b5816fad20d44d1f274b # v3.0.7
        with:
          directory: "env/cloud/app"
          comment-delete: "true"
          comment-title: "Production: app"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      - name: Install Lambda deps
        run: ./aws/lambdas/code/deps.sh install

      - name: Terragrunt plan lambdas
        uses: cds-snc/terraform-plan@28d2efe5155573489fa5b5816fad20d44d1f274b # v3.0.7
        with:
          directory: "env/cloud/lambdas"
          comment-delete: "true"
          comment-title: "Staging: lambdas"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"

      - name: Remove Lambda deps
        run: ./aws/lambdas/code/deps.sh delete

      - name: Terragrunt plan alarms
        uses: cds-snc/terraform-plan@28d2efe5155573489fa5b5816fad20d44d1f274b # v3.0.7
        with:
          directory: "env/cloud/alarms"
          comment-delete: "true"
          comment-title: "Production: alarms"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          terragrunt: "true"
