name: "Terragrunt apply SCRATCH"

on:
  push:
    branches:
      - main
    paths:
      - "aws/**"
      - "env/common/**"
      - "env/scratch/**"
      - ".github/workflows/terragrunt-apply-scratch.yml"

env:
  AWS_REGION: ca-central-1
  AWS_ACCESS_KEY_ID: ${{ secrets.SCRATCH_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SCRATCH_AWS_SECRET_ACCESS_KEY }}
  TERRAFORM_VERSION: 1.0.10
  TERRAGRUNT_VERSION: 0.35.6
  TF_INPUT: false
  TF_VAR_rds_db_password: ${{ secrets.DB_PASSWORD }}

jobs:
  terragrunt-apply:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@3d8debd658c92063839bc97da5c2427100420dec # v1.3.2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Setup Terragrunt
        run: |
          mkdir bin
          wget -O bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v$TERRAGRUNT_VERSION/terragrunt_linux_amd64
          chmod +x bin/*
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721 # v2.10.2
        id: filter
        with:
          filters: |
            common:
              - '.github/workflows/terragrunt-plan-scratch.yml'
              - 'env/common/**'
              - 'env/terragrunt.hcl'
              - 'env/scratch/env_vars.hcl'
            hosted_zone:
              - 'aws/hosted_zone/**'
              - 'env/scratch/hosted_zone/**'
            kms:
              - 'aws/kms/**'
              - 'env/scratch/kms/**'
            network:
              - 'aws/network/**'
              - 'env/scratch/network/**'
            rds:
              - 'aws/rds/**'
              - 'env/scratch/rds/**'
            redis:
              - 'aws/redis/**'
              - 'env/scratch/redis/**'

      # No dependencies
      - name: Terragrunt apply hosted_zone
        if: ${{ steps.filter.outputs.hosted_zone == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: env/scratch/hosted_zone
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Terragrunt apply kms
        if: ${{ steps.filter.outputs.kms == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: env/scratch/kms
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      # Depends on kms
      - name: Terragrunt apply network
        if: ${{ steps.filter.outputs.network == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: env/scratch/network
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      # Depends on network
      - name: Terragrunt apply redis
        if: ${{ steps.filter.outputs.redis == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: env/scratch/redis
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Terragrunt apply rds
        if: ${{ steps.filter.outputs.rds == 'true' || steps.filter.outputs.common == 'true' }}
        working-directory: env/scratch/rds
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

