name: "Terraform security scan"

on:
  push:
    branches: [develop, main]
    paths:
      - "aws/**"
      - ".github/workflows/terraform-security-scan.yml"
  pull_request:
    paths:
      - "aws/**"
      - ".github/workflows/terraform-security-scan.yml"

jobs:
  terraform-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkov security scan
        uses: bridgecrewio/checkov-action@v12 # latest as of Sept 9, 2021
        with:
          directory: aws
          framework: terraform
          output_format: cli
          soft_fail: false
