name: Terraform variable check

on:
  pull_request:
    branches:
      - main
    paths:
      - "aws/**"
      - "env/**"
      - ".github/workflows/**"

jobs:
  terraform-variable-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Check Terraform variables are defined correctly
        run: |
          ./.github/workflows/scripts/terraform-variable-check.sh
