name: "Terragrunt plan all modules STAGING"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  APP_ENV: staging
  APP_DOMAINS: ${{ vars.STAGING_APP_DOMAINS }}
  API_DOMAIN: ${{ vars.STAGING_API_DOMAIN }}
  IDP_DOMAIN: ${{ vars.STAGING_IDP_DOMAIN }}
  AWS_ACCOUNT_ID: ${{ vars.STAGING_AWS_ACCOUNT_ID }}
  AWS_REGION: ca-central-1
  CONFTEST_VERSION: 0.46.0
  TERRAFORM_VERSION: 1.12.2
  TERRAGRUNT_VERSION: 0.83.0
  TF_INPUT: false
  # API
  TF_VAR_zitadel_application_key: ${{ secrets.STAGING_ZITADEL_APPLICATION_KEY }}
  # App
  TF_VAR_ecs_secret_token: ${{ secrets.STAGING_TOKEN_SECRET }}
  TF_VAR_recaptcha_secret: ${{ secrets.STAGING_RECAPTCHA_SITE_SECRET }}
  TF_VAR_recaptcha_public: 6LfJDN4eAAAAAGvdRF7ZnQ7ciqdo1RQnQDFmh0VY
  TF_VAR_notify_callback_bearer_token: ${{ secrets.STAGING_GC_NOTIFY_CALLBACK_BEARER_TOKEN }}
  TF_VAR_notify_api_key: ${{ secrets.STAGING_NOTIFY_API_KEY }}
  TF_VAR_freshdesk_api_key: ${{ secrets.STAGING_FRESHDESK_API_KEY }}
  TF_VAR_sentry_api_key: ${{ secrets.STAGING_SENTRY_API_KEY }}
  TF_VAR_rds_connector_db_password: ${{ secrets.STAGING_DB_PASSWORD_RDS_CONNECTOR }}
  TF_VAR_rds_db_password: ${{ secrets.STAGING_DB_PASSWORD }}
  TF_VAR_slack_webhook: ${{ secrets.STAGING_SLACK_WEBHOOK }}
  TF_VAR_opsgenie_api_key: ${{ secrets.STAGING_OPSGENIE_API_KEY }}
  TF_VAR_gc_temp_token_template_id: b6885d06-d10a-422a-973f-05e274d9aa86
  TF_VAR_gc_template_id: 8d597a1b-a1d6-4e3c-8421-042a2b4158b7
  TF_VAR_cognito_code_template_id: 12a18f84-062c-4a67-8310-bf114af051ea
  TF_VAR_email_address_contact_us: ${{ vars.STAGING_CONTACT_US_EMAIL }}
  TF_VAR_email_address_support: ${{ vars.STAGING_SUPPORT_EMAIL }}
  TF_VAR_load_testing_zitadel_app_private_key: ${{ secrets.STAGING_ZITADEL_APPLICATION_KEY }}
  TF_VAR_zitadel_administration_key: ${{ secrets.STAGING_ZITADEL_ADMINISTRATION_KEY }}
  TF_VAR_hcaptcha_site_verify_key: ${{ secrets.STAGING_HCAPTCHA_SITE_VERIFY_KEY }}
  # IdP
  TF_VAR_idp_database_cluster_admin_username: ${{ secrets.STAGING_IDP_DATABASE_CLUSTER_ADMIN_USERNAME }}
  TF_VAR_idp_database_cluster_admin_password: ${{ secrets.STAGING_IDP_DATABASE_CLUSTER_ADMIN_PASSWORD }}
  TF_VAR_zitadel_admin_password: ${{ secrets.STAGING_ZITADEL_ADMIN_PASSWORD }}
  TF_VAR_zitadel_admin_username: ${{ secrets.STAGING_ZITADEL_ADMIN_USERNAME }}
  TF_VAR_zitadel_database_name: ${{ secrets.STAGING_ZITADEL_DATABASE_NAME }}
  TF_VAR_zitadel_database_user_password: ${{ secrets.STAGING_ZITADEL_DATABASE_USER_PASSWORD }}
  TF_VAR_zitadel_database_user_username: ${{ secrets.STAGING_ZITADEL_DATABASE_USER_USERNAME }}
  TF_VAR_zitadel_secret_key: ${{ secrets.STAGING_ZITADEL_SECRET_KEY }}
  # ECR
  TF_VAR_aws_development_accounts: ${{ vars.AWS_DEVELOPMENT_ACCOUNTS }}
  TF_VAR_cds_org_id: ${{ secrets.STAGING_CDS_ORG_ID }}
  # API END TO END TEST
  TF_VAR_idp_project_identifier: "275372254274006635"
  TF_VAR_api_end_to_end_test_form_identifier: "cmacoc5ga0001yk01zgn888l9"
  TF_VAR_api_end_to_end_test_form_api_private_key: ${{ secrets.STAGING_API_END_TO_END_TEST_FORM_API_PRIVATE_KEY }}

jobs:
  terragrunt-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Setup Terraform, Terragrunt, and Conftest
      - name: Setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/forms-terraform-plan
          role-session-name: TFPlan
          aws-region: ${{ env.AWS_REGION }}

      # No dependencies
      - name: Terragrunt plan ecr
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/ecr"
          comment: "false"
          terragrunt: "true"

      - name: Terragrunt plan hosted_zone
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/hosted_zone"
          comment: "false"
          terragrunt: "true"

      - name: Terragrunt plan kms
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/kms"
          comment: "false"
          terragrunt: "true"

      - name: Terragrunt plan oidc_roles
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/oidc_roles"
          comment: "false"
          terragrunt: "true"

      - name: Terragrunt plan sqs
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/sqs"
          comment: "false"
          terragrunt: "true"

      - name: Terragrunt plan secrets
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/secrets"
          comment: "false"
          terragrunt: "true"

      - name: Terragrunt plan s3
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/s3"
          comment: "false"
          terragrunt: "true"

      # Depends on S3
      - name: Terragrunt plan guard_duty
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/guard_duty"
          comment: "false"
          terragrunt: "true"

      # Depends on kms
      - name: Terragrunt plan sns
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/sns"
          comment: "false"
          terragrunt: "true"

      - name: Terragrunt plan cognito
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/cognito"
          comment: "false"
          terragrunt: "true"

      - name: Terragrunt plan network
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/network"
          comment: "false"
          terragrunt: "true"

      - name: Terragrunt plan dynamodb
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/dynamodb"
          comment: "false"
          terragrunt: "true"

      # Depends on network
      - name: Terragrunt plan load_balancer
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/load_balancer"
          comment: "false"
          terragrunt: "true"

      - name: Terragrunt plan redis
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/redis"
          comment: "false"
          terragrunt: "true"

      - name: Terragrunt plan rds
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/rds"
          comment: "false"
          terragrunt: "true"

      - name: Terragrunt plan idp
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/idp"
          comment: "false"
          terragrunt: "true"

      # Depends on everything
      - name: Terragrunt plan app
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/app"
          comment: "false"
          terragrunt: "true"

      - name: Terragrunt plan api
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/api"
          comment: "false"
          terragrunt: "true"

      - name: Terragrunt plan lambdas
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/lambdas"
          comment: "false"
          terragrunt: "true"

      - name: Terragrunt plan alarms
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/alarms"
          comment: "false"
          terragrunt: "true"

      - name: Terragrunt plan load_testing
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/load_testing"
          comment: "false"
          terragrunt: "true"

      - name: Terragrunt plan pr_review
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/pr_review"
          comment: "false"
          terragrunt: "true"

      - name: Terragrunt plan glue
        uses: cds-snc/terraform-plan@e710cb1446e5dfe69a0182603fb06b5282d7eb07 # v3.4.3
        with:
          directory: "env/cloud/glue"
          comment: "false"
          terragrunt: "true"
